// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBaseFirst.Models
{
    public partial class GetDeptManagerHireDateFormattedResult
    {
        [StringLength(50)]
        public string Dept_Name { get; set; }
        [Column("Manager Name")]
        [StringLength(50)]
        public string ManagerName { get; set; }
        [Column("Formatted Hire Date")]
        [StringLength(50)]
        public string FormattedHireDate { get; set; }
    }
}
