// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBaseFirst.Models
{
    public partial class GetStudentDeptInfoResult
    {
        [StringLength(50)]
        public string Dept_Name { get; set; }
        [Column("Student Full Name")]
        [StringLength(61)]
        public string StudentFullName { get; set; }
    }
}
