// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class InsCourse
{
    public int InsId { get; set; }

    public int CrsId { get; set; }

    public string Evaluation { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Instructor Ins { get; set; }
}