// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using DataBaseFirst.Models;

namespace DataBaseFirst.Models
{
    public partial class ITIContext
    {

        [DbFunction("CheckStudentNameNulls", "dbo")]
        public static string CheckStudentNameNulls(int? StudentID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetDeptManagerHireDateFormatted", "dbo")]
        public IQueryable<GetDeptManagerHireDateFormattedResult> GetDeptManagerHireDateFormatted(int? FormatCode)
        {
            return FromExpression(() => GetDeptManagerHireDateFormatted(FormatCode));
        }

        [DbFunction("GetMonthNameFromDate", "dbo")]
        public static string GetMonthNameFromDate(DateOnly? InputDate)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetNumbersBetween", "dbo")]
        public IQueryable<GetNumbersBetweenResult> GetNumbersBetween(int? StartInt, int? EndInt)
        {
            return FromExpression(() => GetNumbersBetween(StartInt, EndInt));
        }

        [DbFunction("GetStudentDeptInfo", "dbo")]
        public IQueryable<GetStudentDeptInfoResult> GetStudentDeptInfo(int? StudentNo)
        {
            return FromExpression(() => GetStudentDeptInfo(StudentNo));
        }

        [DbFunction("GetStudentNameBasedOnSpecificFormat", "dbo")]
        public IQueryable<GetStudentNameBasedOnSpecificFormatResult> GetStudentNameBasedOnSpecificFormat(string format)
        {
            return FromExpression(() => GetStudentNameBasedOnSpecificFormat(format));
        }

        [DbFunction("GetStudentNameById", "dbo")]
        public static string GetStudentNameById(int? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetStudentNameByType", "dbo")]
        public IQueryable<GetStudentNameByTypeResult> GetStudentNameByType(string NameType)
        {
            return FromExpression(() => GetStudentNameByType(NameType));
        }

        [DbFunction("ReturnDataFromInstractorById", "dbo")]
        public IQueryable<ReturnDataFromInstractorByIdResult> ReturnDataFromInstractorById(int? id)
        {
            return FromExpression(() => ReturnDataFromInstractorById(id));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetDeptManagerHireDateFormattedResult>().HasNoKey();
            modelBuilder.Entity<GetNumbersBetweenResult>().HasNoKey();
            modelBuilder.Entity<GetStudentDeptInfoResult>().HasNoKey();
            modelBuilder.Entity<GetStudentNameBasedOnSpecificFormatResult>().HasNoKey();
            modelBuilder.Entity<GetStudentNameByTypeResult>().HasNoKey();
            modelBuilder.Entity<ReturnDataFromInstractorByIdResult>().HasNoKey();
        }
    }
}
