// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBaseFirst.Models
{
    public partial class ReturnDataFromInstractorByIdResult
    {
        public int Ins_Id { get; set; }
        [StringLength(50)]
        public string Ins_Name { get; set; }
        [StringLength(50)]
        public string Ins_Degree { get; set; }
        [Column("Salary", TypeName = "money")]
        public decimal? Salary { get; set; }
        public int? Dept_Id { get; set; }
    }
}
