// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class StudentAudit
{
    public string ServerUserName { get; set; }

    public DateTime? AuditDate { get; set; }

    public string Note { get; set; }
}