// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class StudentInDeptView
{
    public int StId { get; set; }

    public string StFname { get; set; }

    public string DeptName { get; set; }
}