// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class GetNameAndCourseAndGrade1
{
    public string StFname { get; set; }

    public string CrsName { get; set; }

    public int? Grade { get; set; }
}