// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataBaseFirst.Models
{
    public partial class GetStudentNameBasedOnSpecificFormatResult
    {
        public int? StId { get; set; }
        [StringLength(20)]
        public string StName { get; set; }
    }
}
