// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataBaseFirst.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataBaseFirst.Models
{
    public partial interface IITIContextProcedures
    {
        Task<List<GetStudentsPerDepartmentResult>> GetStudentsPerDepartmentAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_GetDataOfStudentByIdDboResult>> Sp_GetDataOfStudentByIdDboAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Sp_GetDataOfStudentByIdHRResult>> Sp_GetDataOfStudentByIdHRAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetStudentByIdResult>> SP_GetStudentByIdAsync(int? stId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
