// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class SelectFormStudentAndDepartment
{
    public string StFname { get; set; }

    public int? StAge { get; set; }

    public int DeptId { get; set; }

    public string DeptName { get; set; }
}