// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataBaseFirst.Models;

public partial class VwInstructorDepartment
{
    public string InstructorName { get; set; }

    public string DepartmentName { get; set; }
}